# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialog_Patient.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(789, 599)
        self.labelNumero = QtWidgets.QLabel(Dialog)
        self.labelNumero.setGeometry(QtCore.QRect(30, 60, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelNumero.setFont(font)
        self.labelNumero.setObjectName("labelNumero")
        self.labelNom = QtWidgets.QLabel(Dialog)
        self.labelNom.setGeometry(QtCore.QRect(30, 200, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelNom.setFont(font)
        self.labelNom.setObjectName("labelNom")
        self.labelPrenom = QtWidgets.QLabel(Dialog)
        self.labelPrenom.setGeometry(QtCore.QRect(30, 340, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelPrenom.setFont(font)
        self.labelPrenom.setObjectName("labelPrenom")
        self.labelDateNaissance = QtWidgets.QLabel(Dialog)
        self.labelDateNaissance.setGeometry(QtCore.QRect(510, 60, 271, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelDateNaissance.setFont(font)
        self.labelDateNaissance.setObjectName("labelDateNaissance")
        self.pushButtonAjouterPatient = QtWidgets.QPushButton(Dialog)
        self.pushButtonAjouterPatient.setGeometry(QtCore.QRect(30, 480, 211, 91))
        self.pushButtonAjouterPatient.setObjectName("pushButtonAjouterPatient")
        self.pushButtonSupprimerPatient = QtWidgets.QPushButton(Dialog)
        self.pushButtonSupprimerPatient.setGeometry(QtCore.QRect(260, 480, 211, 91))
        self.pushButtonSupprimerPatient.setObjectName("pushButtonSupprimerPatient")
        self.dateEditDateNaissance = QtWidgets.QDateEdit(Dialog)
        self.dateEditDateNaissance.setGeometry(QtCore.QRect(510, 120, 191, 41))
        self.dateEditDateNaissance.setObjectName("dateEditDateNaissance")
        self.lineEditNumero = QtWidgets.QLineEdit(Dialog)
        self.lineEditNumero.setGeometry(QtCore.QRect(30, 120, 231, 41))
        self.lineEditNumero.setObjectName("lineEditNumero")
        self.lineEditNom = QtWidgets.QLineEdit(Dialog)
        self.lineEditNom.setGeometry(QtCore.QRect(30, 260, 231, 41))
        self.lineEditNom.setObjectName("lineEditNom")
        self.lineEditPrenom = QtWidgets.QLineEdit(Dialog)
        self.lineEditPrenom.setGeometry(QtCore.QRect(30, 400, 231, 41))
        self.lineEditPrenom.setObjectName("lineEditPrenom")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelNumero.setText(_translate("Dialog", "Numéro du patient"))
        self.labelNom.setText(_translate("Dialog", "Nom du patient"))
        self.labelPrenom.setText(_translate("Dialog", "Prénom du patient"))
        self.labelDateNaissance.setText(_translate("Dialog", "Date de naissance du patient"))
        self.pushButtonAjouterPatient.setText(_translate("Dialog", "Ajouter patient"))
        self.pushButtonSupprimerPatient.setText(_translate("Dialog", "Supprimer patient"))
