# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialog_Recherche.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(994, 688)
        self.labelNomFournisseur = QtWidgets.QLabel(Dialog)
        self.labelNomFournisseur.setGeometry(QtCore.QRect(20, 20, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelNomFournisseur.setFont(font)
        self.labelNomFournisseur.setObjectName("labelNomFournisseur")
        self.comboBoxNomFournisseur = QtWidgets.QComboBox(Dialog)
        self.comboBoxNomFournisseur.setGeometry(QtCore.QRect(20, 60, 191, 41))
        self.comboBoxNomFournisseur.setObjectName("comboBoxNomFournisseur")
        self.listViewNomFournisseur = QtWidgets.QListView(Dialog)
        self.listViewNomFournisseur.setGeometry(QtCore.QRect(20, 120, 671, 361))
        self.listViewNomFournisseur.setObjectName("listViewNomFournisseur")
        self.pushButtonAfficher = QtWidgets.QPushButton(Dialog)
        self.pushButtonAfficher.setGeometry(QtCore.QRect(290, 60, 211, 41))
        self.pushButtonAfficher.setObjectName("pushButtonAfficher")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelNomFournisseur.setText(_translate("Dialog", "Nom fournisseur"))
        self.pushButtonAfficher.setText(_translate("Dialog", "Afficher"))
