# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Page_Principale.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1074, 829)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.France))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelAccueil = QtWidgets.QLabel(self.centralwidget)
        self.labelAccueil.setGeometry(QtCore.QRect(170, 20, 741, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.labelAccueil.setFont(font)
        self.labelAccueil.setObjectName("labelAccueil")
        self.pushButtonPatient = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonPatient.setGeometry(QtCore.QRect(40, 190, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonPatient.setFont(font)
        self.pushButtonPatient.setObjectName("pushButtonPatient")
        self.pushButtonRecherche = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonRecherche.setGeometry(QtCore.QRect(820, 570, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonRecherche.setFont(font)
        self.pushButtonRecherche.setObjectName("pushButtonRecherche")
        self.pushButtonFournisseur = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonFournisseur.setGeometry(QtCore.QRect(830, 180, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonFournisseur.setFont(font)
        self.pushButtonFournisseur.setObjectName("pushButtonFournisseur")
        self.pushButtonMedicament = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonMedicament.setGeometry(QtCore.QRect(40, 570, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonMedicament.setFont(font)
        self.pushButtonMedicament.setObjectName("pushButtonMedicament")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1074, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelAccueil.setText(_translate("MainWindow", "Bienvenue à l\'application de la pharmacie HealthCare !"))
        self.pushButtonPatient.setText(_translate("MainWindow", "Patient"))
        self.pushButtonRecherche.setText(_translate("MainWindow", "Recherche"))
        self.pushButtonFournisseur.setText(_translate("MainWindow", "Fournisseur"))
        self.pushButtonMedicament.setText(_translate("MainWindow", "Médicament"))
